name: check-flake
run-name: "Check Flake"
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        name: "Install Nix"

      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: "Setup Nix cache"

      - uses: actions/checkout@v4
        name: "Checkout repository"

      - run: nix flake check
        name: "Check Flake"
