name: "flutter-pi-builder"
run-name: "Flutter Pi builder generation"
on:
  push:
    branches:
      - main
    paths:
      - embedder/**
jobs:
  generate-flutter-pi-builder:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: flutter-pi-builder
          build-context: embedder
          dockerfile: embedder/builder.Dockerfile
