name: "firmware-builder"
run-name: "Flutter vending machine firmware builder"
on:
  push:
    branches:
      - main
    paths-ignore:
      - embedder/**
      - README
jobs:
  build-embedder:
    runs-on: ubuntu-latest
    container: ghcr.io/hfxbse/vendo/flutter-pi-builder:latest

    steps:
      - uses: actions/checkout@v3
        name: "Checkout Flutter-Pi submodule"
        with:
          submodules: true

      - run: bash /build.sh
        name: "Build Flutter Pi"
        working-directory: ./embedder/flutter-pi

  build-firmware:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - uses: subosito/flutter-action@v2
        name: "Setup Flutter SDK"
        with:
          channel: "stable"

      - run: flutter config --no-analytics
        name: "Disable Flutter analytics"

      - run: flutter pub get
        name: "Get Flutter dependencies"

      - run: dart run flutterpi_tool build --arch=arm64 --cpu=pi3 --release
        name: "Compile Flutter application"

      - name: "Archive firmware"
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: firmware.zip
          path: ./firmware
          command: "mv ./build/flutter_assets ./firmware"
