name: "test-runner"
run-name: "Run all tests"
on:
  push:
    paths-ignore:
      - embedder/**
      - README
jobs:
  test-firmware:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"

      - uses: subosito/flutter-action@v2
        name: "Setup Flutter SDK"
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          flutter-version: 3.16.7

      - run: flutter config --no-analytics
        name: "Disable Flutter analytics"

      - run: flutter pub get --precompile
        name: "Get Flutter dependencies"

      - run: dart run build_runner:build_runner build
        name: "Generate generated source files"

      - run: flutter test
        name: "Run tests"

      - uses: thedoctor0/zip-release@0.7.5
        name: "Archive failure images"
        if: ${{ failure() }}
        with:
          type: zip
          exclusions: "*.dart"
          filename: ./golden-failures.zip
          path: test

      - uses: actions/upload-artifact@v4
        name: "Upload failure image archive artifact"
        if: ${{ failure() }}
        with:
          name: golden-failure
          path: golden-failures.zip

