name: "test-runner"
run-name: "Run all tests"
on:
  push:
    paths-ignore:
      - embedder/**
      - README
jobs:
  test-firmware:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        name: "Install Nix"

      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: "Setup Nix cache"

      - uses: actions/checkout@v4
        name: "Checkout repository"

      - run: nix run .#tests
        name: "Run all tests"

      - uses: thedoctor0/zip-release@0.7.5
        name: "Archive failure images"
        if: ${{ failure() }}
        with:
          type: zip
          exclusions: "*.dart"
          filename: ./golden-failures.zip
          path: test

      - uses: actions/upload-artifact@v4
        name: "Upload failure image archive artifact"
        if: ${{ failure() }}
        with:
          name: golden-failure
          path: golden-failures.zip

